### ISSUE TITLE
Connected/Redirected Messages Not Showing

### ISSUE THREAD

**Issue by dgleks** [lisdude/toastcore#3]
This is more of an issue with the switch_player builtin directly, but I've filed it here because it stems from code that's ToastCore specific.

Ever since the change to using switch_player instead of return in do_login_command, the MOO no longer displays the *** Connected *** and *** Redirecting *** messages. While I wouldn't call it an issue per say, it is a little annoying given that I rely on those strings for certain triggers. My suggestion is to make switch_player actually print these strings, similar to how return does.

Is this possible? Am I being too anal?

Thanks in advance!

**Comment by lisdude** [comment]
There was talk of showing connection messages if one side of the redirection was an unconnected connection (negative object number). That way using switch_player for connections would work the same as returning in do_login_command, but switching an already connected player wouldn't display superfluous connection messages. That's probably what I'll do unless there are factors I'm not considering.

**Comment by distantorigin** [comment]
I started work on this but, as usual, got pulled in other directions due to ...things...

My solution was changing player_connected_silent over to being a dedicated function just for switching players, since there's nothing else really using it, then adding the checks there. I recall something about checking ahead of time in bf_switch_player to handle redirections, but elaboration should probably be moved over to ToastStunt because this isn't really relevant to ToastCore.

**Comment by dgleks** [comment]
Both ideas sound like they'd work! What if switch_player was updated to accept a third (optional) argument, whether or not to silently perform the switch? Not providing this argument would default to silent being 0.

Also apologies if this was the wrong place to open this issue. I'll attempt to direct issues that are directly server-related to the Toast Stunt repository from now on. Is there any way to move issues from 1 repository to another? Should I simply close this one and open a similar one on the ToastStunt page?

**Comment by distantorigin** [comment]
Thanks. This is now at https://github.com/lisdude/toaststunt/issues/17
